# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltimestamp', models.DateTimeField(auto_now_add=True)),
                ('profile_id', models.CharField(db_index=True, max_length=10)),
                ('account', models.CharField(db_index=True, max_length=15)),
                ('closing_balance', models.FloatField(default=0)),
                ('bonus_closing_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=10)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(default='NA', max_length=30)),
                ('nickname', models.CharField(default='NA', max_length=30)),
                ('institution_name', models.CharField(max_length=100)),
                ('institution_branchcode', models.CharField(default='NA', max_length=30)),
                ('institution_code', models.CharField(default='NA', max_length=30)),
                ('account_type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('group_account', models.CharField(db_index=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('group_account', models.CharField(db_index=True, max_length=15)),
                ('profile_id', models.CharField(max_length=10)),
                ('admin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltimestamp', models.DateTimeField(auto_now_add=True)),
                ('profile_id', models.CharField(db_index=True, max_length=10)),
                ('account', models.CharField(db_index=True, max_length=15)),
                ('trans_type', models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=10)),
                ('service', models.CharField(db_index=True, max_length=25)),
                ('channel', models.CharField(db_index=True, default='NA', max_length=25)),
                ('amount', models.CharField(max_length=25)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('reference', models.CharField(db_index=True, default='NA', max_length=15)),
                ('obal', models.FloatField(default=0)),
                ('cbal', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=20)),
                ('fulltimestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(default='NA', max_length=1024)),
                ('read_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('PREMIUM', 'premium'), ('PROFESSIONAL', 'professional')], max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltimestamp', models.DateTimeField(auto_now_add=True)),
                ('profile_id', models.CharField(db_index=True, max_length=10)),
                ('account', models.CharField(db_index=True, max_length=15)),
                ('msisdn', models.CharField(db_index=True, default='NA', max_length=10)),
                ('external_walletid', models.CharField(default='NA', max_length=25)),
                ('service', models.CharField(db_index=True, max_length=25)),
                ('channel', models.CharField(db_index=True, default='NA', max_length=25)),
                ('dest_account', models.CharField(db_index=True, default='NA', max_length=25)),
                ('amount', models.CharField(max_length=25)),
                ('charge', models.CharField(default='0', max_length=25)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('reference', models.CharField(db_index=True, default='NA', max_length=15)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='DONE', max_length=4)),
                ('resultcode', models.CharField(db_index=True, default='111', max_length=3)),
                ('message', models.TextField(default='NA', max_length=1024)),
                ('processed_timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
