# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('account', models.CharField(db_index=True, max_length=15)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('nickname', models.CharField(max_length=25)),
                ('balance', models.FloatField()),
                ('ts_balance', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')])),
                ('external_walletid', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltimestamp', models.DateTimeField(auto_now_add=True)),
                ('profile_id', models.CharField(db_index=True, max_length=10)),
                ('account', models.CharField(db_index=True, max_length=15)),
                ('closing_balance', models.FloatField(default=0)),
                ('bonus_closing_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=10)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('institution_name', models.CharField(max_length=100)),
                ('institution_branchcode', models.CharField(default='NA', max_length=30)),
                ('institution_code', models.CharField(default='NA', max_length=30)),
                ('account_type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('group_account', models.CharField(db_index=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('group_account', models.CharField(db_index=True, max_length=15)),
                ('profile_id', models.CharField(max_length=10)),
                ('admin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('kyc_type', models.CharField(max_length=15)),
                ('id_type', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=20)),
                ('fulltimestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(default='NA', max_length=1024)),
                ('read_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltimestamp', models.DateTimeField(auto_now_add=True)),
                ('profile_id', models.CharField(db_index=True, max_length=10)),
                ('account', models.CharField(db_index=True, max_length=15)),
                ('msisdn', models.CharField(db_index=True, default='NA', max_length=10)),
                ('external_walletid', models.CharField(max_length=25)),
                ('trans_type', models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=10)),
                ('service', models.CharField(db_index=True, max_length=25)),
                ('amount', models.CharField(max_length=25)),
                ('charge', models.CharField(default='0', max_length=25)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('reference', models.CharField(db_index=True, default='NA', max_length=15)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='DONE', max_length=4)),
                ('resultcode', models.CharField(db_index=True, default='111', max_length=3)),
                ('message', models.TextField(default='NA', max_length=1024)),
                ('obal', models.FloatField(default=0)),
                ('cbal', models.FloatField(default=0)),
                ('processed_timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
