# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumusers',
            name='level',
            field=models.CharField(choices=[('STANDARD', 'standard'), ('PREMIUM', 'premium')], max_length=10),
        ),
    ]
