# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochi', '0002_auto_20171119_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_entity', models.CharField(max_length=100)),
                ('ext_acc_no', models.CharField(default='NA', max_length=30)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('success', 'SUCCESS'), ('failed', 'FAILED'), ('pending', 'PENDING')], default='pending', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=8)),
                ('charge', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='GroupMember',
        ),
        migrations.RenameModel(
            old_name='PremiumUsers',
            new_name='PaidUser',
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='account_type',
            field=models.CharField(choices=[('MM', 'MOBILE MONEY'), ('BA', 'BANK ACCOUNT')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.CharField(db_index=True, default='GL0001', max_length=15),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='profile_id',
            field=models.CharField(db_index=True, default='POC0GL0001', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(choices=[('P2P', 'P2P'), ('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW'), ('BONUS', 'BONUS')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='PENDING', max_length=4),
        ),
    ]
