# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochi', '0003_auto_20171127_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesnapshot',
            old_name='fulltimestamp',
            new_name='full_timestamp',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='cbal',
            new_name='c_bal',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='fulltimestamp',
            new_name='full_timestamp',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='obal',
            new_name='o_bal',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='fulltimestamp',
            new_name='full_timestamp',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='external_walletid',
            new_name='external_wallet_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='fulltimestamp',
            new_name='full_timestamp',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='resultcode',
            new_name='result_code',
        ),
        migrations.AddField(
            model_name='group',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
