# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochi', '0004_auto_20171129_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('pochi', 'POCHI'), ('mobile', 'MOBILE'), ('bank', 'BANK'), ('cash', 'CASH')], db_index=True, default='pochi', max_length=6),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='PENDING', max_length=7),
        ),
    ]
