# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochi', '0005_auto_20171211_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='trans_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paiduser',
            name='level',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('POCHI', 'Pochi'), ('MOBILE', 'Mobile'), ('BANK', 'Bank'), ('CASH', 'Cash')], db_index=True, default='POCHI', max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(choices=[('P2P', 'p2p'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('INTEREST', 'Interest')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=7),
        ),
    ]
