# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochi', '0006_auto_20171211_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiduser',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='paiduser',
            name='level',
            field=models.CharField(choices=[('STANDARD', 'Free'), ('PREMIUM', 'Premium')], max_length=10),
        ),
    ]
