# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochi', '0008_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
