# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-07 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochi', '0009_auto_20171215_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalaccount',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='rate',
            name='full_timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
