# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fimcosite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='external_walletid',
            new_name='external_wallet_id',
        ),
        migrations.AddField(
            model_name='account',
            name='allow_overdraft',
            field=models.BooleanField(default=0),
        ),
    ]
