# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fimcosite', '0002_auto_20171127_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_id',
            field=models.CharField(db_index=True, default='NA', max_length=10),
        ),
    ]
