# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fimcosite', '0003_auto_20171211_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_superuser',
        ),
    ]
