# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fimcosite', '0004_auto_20171211_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('pending', 'PENDING')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('individual', 'INDIVIDUAL'), ('corporate', 'CORPORATE')], default='individual', max_length=10),
        ),
    ]
