# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fimcosite', '0005_auto_20171211_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('I', 'Individual'), ('C', 'Corporate')], default='I', max_length=1),
        ),
    ]
