# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fimcosite', '0006_auto_20171211_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateprofile',
            name='website',
        ),
    ]
