# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-07 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fimcosite', '0007_remove_corporateprofile_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='approval_status',
        ),
    ]
