# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrenctAccountMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAccountYearly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('base_currency', models.CharField(max_length=4)),
                ('counter_currency', models.CharField(max_length=4)),
                ('change', models.DecimalField(decimal_places=4, max_digits=6)),
                ('current_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('record_datetime', models.DateTimeField()),
                ('prev_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('prev_rate_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='ImportExportMonthy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('import_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('export_value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ImportExportYearly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('import_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('export_value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='LiborRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('value_date', models.DateTimeField()),
                ('overnight_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('m1_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('m3_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('m6_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('m12_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OvernightInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('current_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('record_datetime', models.DateTimeField()),
                ('weighted_avg_rate', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tbill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('record_datetime', models.DateTimeField()),
                ('due_date', models.DateField()),
                ('no_of_bids', models.IntegerField()),
                ('no_of_successful_bids', models.IntegerField()),
                ('highest_bid_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lowest_bid_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('minimum_success_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weighted_avg_price_success', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weighted_avg_yield_annum', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount_offered', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_tender', models.DecimalField(decimal_places=2, max_digits=6)),
                ('under_over_subscribed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('successful_bids', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tbond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('record_datetime', models.DateTimeField()),
                ('redemption_date', models.DateField()),
                ('no_of_bids', models.IntegerField()),
                ('no_of_successful_bids', models.IntegerField()),
                ('minimum_successful_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weighted_avg_price_success', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weighted_avg_to_maturity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weigted_avg_coupon_yield', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount_offered', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_tender', models.DecimalField(decimal_places=2, max_digits=6)),
                ('under_over_subscribed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('successful_bids', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
