# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fimcoplatform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrenctAccountMonthly',
            new_name='CurrentAccountMonthly',
        ),
        migrations.RenameModel(
            old_name='ImportExportMonthy',
            new_name='ImportExportMonthly',
        ),
        migrations.RenameField(
            model_name='tbond',
            old_name='weigted_avg_coupon_yield',
            new_name='weighted_avg_coupon_yield',
        ),
        migrations.AddField(
            model_name='overnightinterest',
            name='prev_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overnightinterest',
            name='prev_rate_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='change',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='current_rate',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='prev_rate',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
