# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fimcoplatform', '0002_auto_20171119_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='change',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='current_rate',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='prev_rate',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
