# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fimcoplatform', '0003_auto_20171119_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField()),
                ('base_currency', models.CharField(max_length=4)),
                ('counter_currency', models.CharField(max_length=4)),
                ('change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('record_datetime', models.DateTimeField()),
                ('prev_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('prev_rate_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CurrentAccountMonthly',
            new_name='CurrentMonthlyAccount',
        ),
        migrations.RenameModel(
            old_name='CurrentAccountYearly',
            new_name='CurrentYearlyAccount',
        ),
        migrations.RenameModel(
            old_name='LiborRates',
            new_name='LiborRate',
        ),
        migrations.RenameModel(
            old_name='ImportExportMonthly',
            new_name='MonthlyImportExport',
        ),
        migrations.RenameModel(
            old_name='ImportExportYearly',
            new_name='YearlyImportExport',
        ),
        migrations.DeleteModel(
            name='ExchangeRates',
        ),
        migrations.AddField(
            model_name='tbill',
            name='type',
            field=models.CharField(default='1-Month', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbond',
            name='type',
            field=models.CharField(default='1Month', max_length=10),
            preserve_default=False,
        ),
    ]
